# Generated by Django 3.2.8 on 2021-10-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='walletDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.TextField()),
                ('private_key', models.TextField()),
                ('nft_contract', models.TextField()),
            ],
        ),
    ]
